// Theme is written in typescript, so it must be built first.
const { defaultTheme: theme } = require('./dist')

module.exports = {
  color: {
    base: theme.colors.grays[9],
    light: theme.colors.grays[8],
    lightest: theme.colors.grays[7],
    link: theme.colors.primary,
    linkHover: theme.colors.greens[5],
    border: theme.colors.grays[2],
    name: theme.colors.greens[6],
    type: theme.colors.red,
    errors: theme.colors.red,
    baseBackground: theme.colors.grays[0],
    codeBackground: theme.colors.grays[1],
    sidebarBackground: theme.colors.grays[1],
    ribbonBackground: theme.colors.greens[0],
    ribbonText: theme.colors.green,
    // codeComment: '#6d6d6d',
    codeComment: theme.colors.grays[8],
    // codePunctuation: '#999',
    codePunctuation: theme.colors.grays[6],
    // codeProperty: '#905',
    codeProperty: theme.colors.greens[5],
    // codeDeleted: '#905',
    codeDeleted: theme.colors.greens[5],
    // codeString: '#690',
    codeString: theme.colors.red,
    // codeInserted: '#690',
    codeInserted: theme.colors.red,
    // codeOperator: '#9a6e3a',
    // codeOperator: '#6D6D6D',
    codeOperator: theme.colors.grays[8],
    // codeKeyword: '#1673b1',
    codeKeyword: theme.colors.accent,
    // codeFunction: '#DD4A68',
    codeFunction: theme.colors.greens[5],
    // codeVariable: '#e90',
    codeVariable: theme.colors.greens[5],
  },
  fontFamily: {
    base: theme.fonts.body,
    monospace: [
      '"DelugiaCode NF"',
      'Cascadia Code',
      '"FuraCode NF"',
      'Fira Code',
      '"Operator Mono"',
      'Dank Mono',
      'Menlo',
      'Consolas',
      '"Liberation Mono"',
      'monospace',
    ],
  },
  borderRadius: 4,
}
